### ISSUE TITLE
Ошибка при создании option с название :send 

### ISSUE THREAD

**Issue by AS-AlStar** [smart-rb/smart_initializer#9]
Возникает ошибка(Неверно количество аргументов), если создать option с название :send - пытается переписать дефолтный метод send.

**Comment by 0exp** [comment]
Привет! Спасибо за ишью.

Хм. Да, надо бы перейти на использование `__send__`, поправлю в ближайшем релизе

**Comment by 0exp** [comment]
Fixed in #10
